name: Typescript Node CI

on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn build
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/hairnerds-studio-rebuild/backend
            git pull origin staging
            git status
            yarn install --only=prod
            pm2 restart hairnerds-studio-api@staging
